// ═══════════════════════════════════════════════════════════
//  NC AI Package Export — Written 100% in NC
//
//  Export NC projects as distributable packages.
//  Supports standalone binary, Docker container,
//  npm package, and zip archive formats.
//
//  Built by DevHeal Labs AI
//
//  Usage:
//    nc nc-ai/nc/export.nc --format binary --project ./my-app
//    nc nc-ai/nc/export.nc --format docker --project ./my-app
//    nc nc-ai/nc/export.nc --format zip --project ./my-app
// ═══════════════════════════════════════════════════════════

service "nc-export"
version "1.0.0"

// ── Scan Project Structure ───────────────────────────────

to scan_project with project_dir:
    purpose: "Analyze project structure and files"
    set result to {
        name: basename(project_dir),
        dir: project_dir,
        services: [],
        pages: [],
        tests: [],
        configs: [],
        total_files: 0
    }

    set files to list_dir_recursive(project_dir)
    repeat for each file in files:
        if file ends with ".nc" and file contains "service":
            append file to result.services
        if file ends with ".nc" and file contains "test":
            append file to result.tests
        if file ends with ".ncui":
            append file to result.pages
        if file ends with ".json" or file ends with ".env":
            append file to result.configs
        set result.total_files to result.total_files + 1

    respond with result

// ── Export as Standalone Binary ──────────────────────────

to export_binary with project_dir:
    purpose: "Compile NC project into a standalone executable"

    set project to scan_project(project_dir)
    set output_dir to project_dir + "/dist"
    mkdir(output_dir)

    log "NC Export — Standalone Binary"
    log "Project: " + project.name
    log "Services: " + length(project.services)
    log "Pages: " + length(project.pages)

    // Compile each service
    repeat for each service_file in project.services:
        set bin_name to replace(basename(service_file), ".nc", "")
        set bin_path to output_dir + "/" + bin_name
        log "  Compiling: " + service_file + " → " + bin_name
        run_cmd("nc build " + service_file + " -o " + bin_path)

    // Build NCUI pages
    repeat for each page_file in project.pages:
        log "  Building UI: " + page_file
        run_cmd("nc-ui release " + page_file + " -o " + output_dir)

    // Copy configs
    repeat for each config_file in project.configs:
        copy_file(config_file, output_dir + "/" + basename(config_file))

    // Create start script
    set start_script to "#!/bin/bash\n"
    set start_script to start_script + "# " + project.name + " — Built with NC\n"
    set start_script to start_script + "# Auto-generated by NC AI Export\n\n"
    repeat for each service_file in project.services:
        set bin_name to replace(basename(service_file), ".nc", "")
        set start_script to start_script + "./" + bin_name + " &\n"
    set start_script to start_script + "\necho \"" + project.name + " started\"\n"
    set start_script to start_script + "echo \"Open http://localhost:8000 in your browser\"\n"
    set start_script to start_script + "wait\n"
    write_file(output_dir + "/start.sh", start_script)
    run_cmd("chmod +x " + output_dir + "/start.sh")

    log "Exported to: " + output_dir
    respond with {format: "binary", output: output_dir, files: project.total_files}

// ── Export as Docker Container ───────────────────────────

to export_docker with project_dir:
    purpose: "Package NC project as Docker container"

    set project to scan_project(project_dir)
    set output_dir to project_dir + "/dist"
    mkdir(output_dir)

    log "NC Export — Docker Container"
    log "Project: " + project.name

    // Generate Dockerfile
    set dockerfile to "# " + project.name + " — Built with NC\n"
    set dockerfile to dockerfile + "# Auto-generated by NC AI Export\n\n"
    set dockerfile to dockerfile + "FROM ubuntu:22.04 AS builder\n"
    set dockerfile to dockerfile + "RUN apt-get update && apt-get install -y curl build-essential\n"
    set dockerfile to dockerfile + "RUN curl -fsSL https://nc-lang.org/install.sh | bash\n\n"
    set dockerfile to dockerfile + "WORKDIR /app\n"
    set dockerfile to dockerfile + "COPY . .\n\n"

    // Build services
    repeat for each service_file in project.services:
        set bin_name to replace(basename(service_file), ".nc", "")
        set dockerfile to dockerfile + "RUN nc build " + basename(service_file) + " -o " + bin_name + "\n"

    // Build UI
    repeat for each page_file in project.pages:
        set dockerfile to dockerfile + "RUN nc-ui release " + basename(page_file) + "\n"

    set dockerfile to dockerfile + "\nFROM ubuntu:22.04\n"
    set dockerfile to dockerfile + "WORKDIR /app\n"
    set dockerfile to dockerfile + "COPY --from=builder /app/dist ./\n"
    set dockerfile to dockerfile + "EXPOSE 8000\n"
    set dockerfile to dockerfile + "CMD [\"./start.sh\"]\n"

    write_file(project_dir + "/Dockerfile", dockerfile)

    // Generate docker-compose.yml
    set compose to "version: '3.8'\n"
    set compose to compose + "services:\n"
    set compose to compose + "  " + project.name + ":\n"
    set compose to compose + "    build: .\n"
    set compose to compose + "    ports:\n"
    set compose to compose + "      - \"8000:8000\"\n"
    set compose to compose + "    restart: unless-stopped\n"
    set compose to compose + "    environment:\n"
    set compose to compose + "      - NC_ENV=production\n"
    write_file(project_dir + "/docker-compose.yml", compose)

    log "Created: Dockerfile, docker-compose.yml"
    log "Run: docker compose up --build"
    respond with {format: "docker", output: project_dir, files: 2}

// ── Export as ZIP Archive ────────────────────────────────

to export_zip with project_dir:
    purpose: "Package NC project as distributable ZIP"

    set project to scan_project(project_dir)
    set zip_name to project.name + "-v1.0.0.zip"
    set zip_path to project_dir + "/" + zip_name

    log "NC Export — ZIP Archive"
    log "Project: " + project.name

    // Build UI first
    repeat for each page_file in project.pages:
        run_cmd("nc-ui release " + page_file)

    // Create README
    set readme to "# " + project.name + "\n\n"
    set readme to readme + "Built with [NC Language](https://nc-lang.org) by DevHeal Labs AI\n\n"
    set readme to readme + "## Quick Start\n\n"
    set readme to readme + "```bash\n"
    set readme to readme + "# Install NC\n"
    set readme to readme + "curl -fsSL https://nc-lang.org/install.sh | bash\n\n"
    set readme to readme + "# Start the backend\n"
    repeat for each s in project.services:
        set readme to readme + "nc serve " + basename(s) + "\n"
    set readme to readme + "\n# Run tests\n"
    repeat for each t in project.tests:
        set readme to readme + "nc run " + basename(t) + "\n"
    set readme to readme + "```\n\n"
    set readme to readme + "## Files\n\n"
    set readme to readme + "| File | Purpose |\n"
    set readme to readme + "|------|---------|\n"
    repeat for each s in project.services:
        set readme to readme + "| " + basename(s) + " | Backend API |\n"
    repeat for each p in project.pages:
        set readme to readme + "| " + basename(p) + " | Frontend UI |\n"
    repeat for each t in project.tests:
        set readme to readme + "| " + basename(t) + " | Tests |\n"

    write_file(project_dir + "/README.md", readme)

    // Create zip
    run_cmd("cd " + project_dir + " && zip -r " + zip_name + " . -x '*.git*' -x 'node_modules/*' -x 'dist/*'")

    log "Exported: " + zip_path
    log "Share this file — recipients just need NC installed to run it"
    respond with {format: "zip", output: zip_path, size: file_size(zip_path)}

// ── Export as NC Package ─────────────────────────────────

to export_package with project_dir:
    purpose: "Create an NC package for nc pkg install"

    set project to scan_project(project_dir)
    log "NC Export — NC Package"

    // Create package.nc manifest
    set manifest to "// NC Package Manifest\n"
    set manifest to manifest + "package \"" + project.name + "\"\n"
    set manifest to manifest + "version \"1.0.0\"\n"
    set manifest to manifest + "author \"DevHeal Labs AI\"\n"
    set manifest to manifest + "license \"MIT\"\n\n"
    set manifest to manifest + "description \"" + project.name + " — Generated by NC AI\"\n\n"
    set manifest to manifest + "files:\n"
    repeat for each s in project.services:
        set manifest to manifest + "    include \"" + basename(s) + "\"\n"
    repeat for each p in project.pages:
        set manifest to manifest + "    include \"" + basename(p) + "\"\n"
    repeat for each t in project.tests:
        set manifest to manifest + "    include \"" + basename(t) + "\"\n"
    set manifest to manifest + "\ndependencies:\n"
    set manifest to manifest + "    nc-lang >= 1.0.0\n"

    write_file(project_dir + "/package.nc", manifest)

    log "Created: package.nc"
    log "Publish: nc pkg publish " + project_dir
    log "Install: nc pkg install " + project.name
    respond with {format: "package", manifest: project_dir + "/package.nc"}

// ── Main Export Handler ──────────────────────────────────

to export_project with project_dir and format:
    purpose: "Export project in the specified format"

    if format is "binary":
        respond with export_binary(project_dir)
    if format is "docker":
        respond with export_docker(project_dir)
    if format is "zip":
        respond with export_zip(project_dir)
    if format is "package" or format is "pkg":
        respond with export_package(project_dir)

    // Default: all formats
    log "NC Export — All Formats"
    set r1 to export_binary(project_dir)
    set r2 to export_docker(project_dir)
    set r3 to export_zip(project_dir)
    set r4 to export_package(project_dir)
    respond with {binary: r1, docker: r2, zip: r3, package: r4}

// ── API Routes ───────────────────────────────────────────

api:
    POST /export          runs export_project
    POST /export/binary   runs export_binary
    POST /export/docker   runs export_docker
    POST /export/zip      runs export_zip
    POST /export/package  runs export_package
